GET http://localhost:8101/10
Accept: application/json

###
GET http://localhost:8101/9/score?score=1000
Accept: application/json

###
GET http://localhost:8001//whtnimaseil123321
Accept: application/json

###
POST http://localhost:8001/decreaseNumber
Content-Type: application/json

[{"id":1, "name":"abc", "number":23},
  {"id":2, "name":"def", "number":11}]

###

GET http://localhost:8201/add

