#\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u7684\u540D\u5B57
spring:
  application:
    name: item-service
# itme  8001, user  8101  ,  order 8201
server:
  port: 8001
eureka:
  client:
    service-url:
      # 默认地点，如果使用云服务，可以从云服务商购买不同地点注册中心服务器，自己搭建的注册中心，只能使用defaultZone
      defaultZone: http://eureka1:2001/eureka
